package com.protogest.service.database.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "protocol_instance")
public class ProtocolInstance {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uuid;

    @DynamoDBAttribute
    private List<FormField> fields;

    @DynamoDBAttribute
    private String userEmail;

    @DynamoDBAttribute
    private String invitedUserEmail;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private Status status = Status.PENDING;


    public enum Status {
        PENDING,
        REJECTED,
        APPROVED
    }

    public enum EFieldType {
        DATE,
        NUMBER,
        STRING,
        BOOL
    }

    @DynamoDBDocument
    public static class FormField {
        private String id;
        private String value;
        private EFieldType type;

        public FormField() {
            // ctor for DynamoDBMapper
        }

        public FormField(String id, String value, EFieldType type) {
            this.id = id;
            this.value = value;
            this.type = type;
        }

        @DynamoDBAttribute(attributeName = "Id")
        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        @DynamoDBAttribute(attributeName = "Value")
        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        @DynamoDBTypeConvertedEnum
        @DynamoDBAttribute(attributeName = "Type")
        public EFieldType getType() {
            return type;
        }

        public void setType(EFieldType type) {
            this.type = type;
        }

    }

    public String getUuid() {
        return uuid;
    }


    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public List<FormField> getFields() {
        return fields;
    }

    public void setFields(List<FormField> fields) {
        this.fields = fields;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }


    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public String getInvitedUserEmail() {
        return invitedUserEmail;
    }

    public void setInvitedUserEmail(String invitedUserEmail) {
        this.invitedUserEmail = invitedUserEmail;
    }
}

