package com.protogest.service.database.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "protocol_schema")
public class ProtocolSchema {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uuid;

    @DynamoDBAttribute
    private Long id;
}
