package com.protogest.service.database.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "session")
public class Session {
    public Session() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uuid;

    @DynamoDBAttribute
    private String authToken;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String connectionDate;


    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


    public String getAuthToken() {
        return authToken;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }


    public String getConnectionDate() {
        return connectionDate;
    }

    public void setConnectionDate(String connectionDate) {
        this.connectionDate = connectionDate;
    }


    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
